### ISSUE TITLE
Keycloack - how to import realm from json config file?

### ISSUE THREAD

**Issue by hughesadam87** [chainguard-images/images#2428]
### Image: cgr.dev/chainguard/keycloak

I can't figure out how to import realms in chainguard's keycloak image.  

For `quay.io/keycloak/keycloak:latest`, one simply adds `realm.json` file under `/opt/keycloack/data/import` and the keycloack instance will bootstrap it on container startup.

``` 
version: '3.8'
services:
  keycloak:
    image: quay.io/keycloak/keycloak:latest
    command: "-v start-dev --import-realm"
    ports:
      - "8080:8080"

    volumes:
      - ./realms:/opt/keycloak/data/import
 ```

However, swapping out for `cgr.dev/chainguard/keycloak:latest`, the realm is no longer loaded.  The container starts fine otherwise.  

Does chaingaurd keycloack image support loading realms/clients from configuration?  If so - does it go in a different container path?

[Keycloack docs](https://www.keycloak.org/server/containers)
![image](https://github.com/chainguard-images/images/assets/1972276/3364d624-f701-4456-b239-9ef12e4cfa3f)
