### ISSUE TITLE
Permissions on Postgres are wrong

### ISSUE THREAD

**Issue by deitch** [chainguard-images/images#275]
The permissions on the Postgres image config [here](https://github.com/chainguard-images/images/blob/main/images/postgres/configs/latest.apko.yaml#L39) are incorrect. It is:

```yaml
paths:
  - path: /var/lib/postgresql/data
    type: directory
    uid: 70
    gid: 70
    permissions: 777
```

But that is interpreted as `uint32`, i.e. 777 (seven hundred and seventy seven), when what we really want is `0o777`, i.e. octal 777 (or `rwxrwxrwx`).
