### ISSUE TITLE
Support for CVE scanning in non-ghcr registry

### ISSUE THREAD

**Issue by jdolitsky** [chainguard-images/images#29]
The current action takes in ghcr.io as an input:
```
    # Scan (only working for GHCR/latest images for now)
    - uses: chainguard-images/actions/vul-scans@main
      id: scans
      # TODO: support for multiple tags in inputs.apkoAdditionalTags
      if: startsWith(inputs.apkoBaseTag, 'ghcr.io/') && inputs.apkoAdditionalTags == 'latest'
      with:
        registry: ghcr.io
        image: ${{ inputs.apkoBaseTag }}
        RUN_SNYK: 'false'
        RUN_GRYPE: 'true'
        DOCKER_LOGIN: 'true'
    
```
