### ISSUE TITLE
Extending base python image with packages

### ISSUE THREAD

**Issue by pettermk** [chainguard-images/images#349]
### Which image/versions are related to this issue/feature request?

python:3.10
python:3.10-dev

### Issue/Feature description

Hi, I am advising users in my company on base images to use in their containers, currently looking into chainguard images and my preliminary tests are very promising! I hope you can help me with the following issue.

Many users in my company use proprietary ODBC drivers in their python app. They are readily available as apks, debs etc., but I can't install these on top of the chainguard base python images. Now, generally, this use case is too specific to ask for a separate chainguard python image with said driver. It is also, in my context, too general to ask all of our teams to solve the problem of getting said drivers into a base image, as this requirement is going to hit many of our teams.

So which direction would you advise in this scenario, I can't ask all teams to setup a build pipeline to create their base images. Is there a way I might have missed, which would make it relatively easy for a user to add such a package on top of the base chainguard python image?

Thanks,
- Petter

**Comment by jdolitsky** [comment]
Hello and thanks for trying our Python image.

Please see using the python dev image and pip in Dockerfile here: https://github.com/chainguard-images/images/tree/main/images/python#usage

Will this work for your scenario?

**Comment by jdolitsky** [comment]
> Is the only option to build our own base image using the apko and melange stack?

If you're looking to add additional pre-built APKs, then I think this may be the proper route. Keep in mind that they should be produced using Wolfi (vs. Alpine) in melange to prevent strange issues mixing APKs. This is of course if you wish to use them alongside the Wolfi python packages

**Comment by dlorenc** [comment]
> install necessary extra drivers from apk packages onto this image,

Could you share with drivers you need?

**Comment by pettermk** [comment]
Thanks for the feedback. We frequently need these drivers for ms sql connectivity

https://learn.microsoft.com/en-us/sql/connect/odbc/download-odbc-driver-for-sql-server?view=sql-server-ver16#download-for-linux-and-macos

I suppose these might give a bit of headache as they are alpine and built against musl, but I don't have any options to rebuild as the drivers are proprietary. If I remember correctly though, the packages are simple and I may be able to unpack the Debian one and extract the driver directly.

**Comment by pettermk** [comment]
I've been at this for a while now - but I am not able to make the drivers run on wolfi linux the same way as I am on debian or fedora. As the drivers are proprietary this is quite difficult. I've tried to build a wolfi package locally, using the debian and RHEL driver, both with this approach
* Extract the files from .deb|.rpm to the file system
* Run post-install scripts
This same approach works on a standard debian or fedora system. The litmus test is running `isql` to connect to an mssql database, and this is the last part of the strace I gather when doing so and it fails

```
openat(AT_FDCWD, "/etc/odbcinst.ini", O_RDONLY) = 3
newfstatat(3, "", {st_mode=S_IFREG|0644, st_size=163, ...}, AT_EMPTY_PATH) = 0
read(3, "[ODBC Driver 18 for SQL Server]\n"..., 4096) = 163
read(3, "", 4096)                       = 0
close(3)                                = 0
openat(AT_FDCWD, "/root/.odbcinst.ini", O_RDONLY) = -1 ENOENT (No such file or directory)
futex(0x7f3b52b2477c, FUTEX_WAKE_PRIVATE, 2147483647) = 0
newfstatat(1, "", {st_mode=S_IFCHR|0620, st_rdev=makedev(0x88, 0), ...}, AT_EMPTY_PATH) = 0
write(1, "[IM004][unixODBC][Driver Manager"..., 83[IM004][unixODBC][Driver Manager]Driver's SQLAllocHandle on SQL_HANDLE_HENV failed
) = 83
write(2, "[ISQL]ERROR: Could not SQLDriver"..., 40[ISQL]ERROR: Could not SQLDriverConnect
) = 40
exit_group(1)                           = ?
+++ exited with 1 +++
```

I'm at wits end here and don't know how to proceed with debugging. You may call this a fool's errand, the driver being proprietary and all, however we're really keen to be able to use chainguard images and really hope we can crack this one.

The only lead I've not been able to follow through at this point is a difference in the output of `ldd` for the driver library, they are equal on wolfi vs debian with the exception of `libltdl.so.7` being resolved on debian, but does not show up on wolfi. This is the full output

```
        linux-vdso.so.1 (0x00007fff227b0000)
        libdl.so.2 => /lib/x86_64-linux-gnu/libdl.so.2 (0x00007f5ea1e8c000)
        librt.so.1 => /lib/x86_64-linux-gnu/librt.so.1 (0x00007f5ea1e82000)
        libodbcinst.so.2 => /usr/lib/x86_64-linux-gnu/libodbcinst.so.2 (0x00007f5ea1e6a000)
        libkrb5.so.3 => /usr/lib/x86_64-linux-gnu/libkrb5.so.3 (0x00007f5ea1d90000)
        libgssapi_krb5.so.2 => /usr/lib/x86_64-linux-gnu/libgssapi_krb5.so.2 (0x00007f5ea1d3d000)
        libstdc++.so.6 => /usr/lib/x86_64-linux-gnu/libstdc++.so.6 (0x00007f5ea1b70000)
        libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007f5ea1a2a000)
        libgcc_s.so.1 => /lib/x86_64-linux-gnu/libgcc_s.so.1 (0x00007f5ea1a10000)
        libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007f5ea19ee000)
        libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007f5ea1819000)
        /lib64/ld-linux-x86-64.so.2 (0x00007f5ea22a7000)
        libltdl.so.7 => /usr/lib/x86_64-linux-gnu/libltdl.so.7 (0x00007f5ea180e000)
```

This may have some relation, as the library is bundled with an `.rll` file which I don't really know how it gets loaded. I'd be grateful for any other leads or things I could do to debug this further, thanks.

**Comment by pettermk** [comment]
I seem to have resolved it - it was the `glibc-iconv` package which was missing

**Comment by dlorenc** [comment]
Wow thanks! Could you share the config?

**Comment by pettermk** [comment]
Sure yeah, this seems to do the job.
However, it will not work as a standalone package, because if there were multiple odbc packages installed they would clobber each others `/etc/odbcinst.ini`. The last pipeline step does what the `post-install` script should be doing, but it seems that `apko` will not run the post-install scripts and therefore I had to make this workaround in the package config script. Maybe this step could be moved into a Dockerfile :thinking: 

```yaml
package:
  name: msodbcsql18
  version: 18.2.1
  description: MS odbc driver for SQL Server
  target-architecture:
    - linux/amd64
  copyright:
    - license: Apache-2.0
      paths:
        - "*"
  scriptlets:
    post-install: |
      #!/bin/busybox sh
      /usr/bin/odbcinst -i -d -f /opt/microsoft/msodbcsql18/etc/odbcinst.ini
  dependencies:
    runtime:
      - wolfi-base
      - unixodbc
      - ca-certificates-bundle
      - openssl
      - glibc
      - glibc-iconv
      - libstdc++
      - krb5

environment:
  contents:
    repositories:
      - https://packages.wolfi.dev/os
    packages:
      - wolfi-base
      - busybox
      - ca-certificates-bundle
      - wget
      - unixodbc
      - xz
      - gnutar
      - dpkg

pipeline:
  - name: Download mssql driver
    runs: |
      wget https://packages.microsoft.com/debian/11/prod/pool/main/m/msodbcsql18/msodbcsql18_${{package.version}}.1-1_amd64.deb
      mkdir -p ${{targets.destdir}}/etc
      dpkg-deb -x -v msodbcsql18_${{package.version}}.1-1_amd64.deb ${{targets.destdir}}
  - name: Install the mssql driver
    runs: |
      cp ${{targets.destdir}}/opt/microsoft/msodbcsql18/etc/odbcinst.ini ${{targets.destdir}}/etc/odbcinst.ini
      echo "UsageCount=1" >> ${{targets.destdir}}/etc/odbcinst.ini
      echo >> ${{targets.destdir}}/etc/odbcinst.ini
```
