### ISSUE TITLE
Allow environment variables to configure nginx using templates

### ISSUE THREAD

**Issue by marcofranssen** [chainguard-images/images#93]

**Comment by amouat** [comment]
This sounds good, but what do we need to enable? There's a couple of issues with the nginx build that I want to get fixed asap.

**Comment by marcofranssen** [comment]
I will come back to the details. We basically need some nginx configs and some `envsubst` to inject those things into the nginx conf. I'll do some anatomy on the official nginx image.

**Comment by marcofranssen** [comment]
We will need to put in place some templates and this custom entrypoint.

https://github.com/nginxinc/docker-nginx/blob/master/entrypoint/20-envsubst-on-templates.sh

With some guidance I would love to give this a shot on the nginx image.

**Comment by amouat** [comment]
Let me pull in @rawlingsj 

We are about to switch this image to a wolfi based image, it would good to make these changes at the same time.

**Comment by marcofranssen** [comment]
Awesome. I would love to do my first contribution, so looking forward to assist. Keep me in the loop so I can learn.

**Comment by amouat** [comment]
Ok, will do. Basically most of the changes will need to happen at the melange level: https://github.com/wolfi-dev/os/blob/main/nginx.yaml. That's how the nginx package gets built.

**Comment by rawlingsj** [comment]
I must admit I've not always been a fan of using secrets as env vars, I've seen recommendations in the past that say it's better to have secrets in a file that get's mounted as a volume into a container.  

Having said that it's probably worth having a consistent experience with the official image.  We have an example of using an entry point script that @marcofranssen you could look at taking the same approach


We can add the script into this folder https://github.com/wolfi-dev/os/tree/main/nginx

and reference it as a subpackage like this https://github.com/wolfi-dev/os/blob/22d2da06a9d52373787b3ab2ca2bd00b6bd98e04/postgresql-11.yaml#L77-L86

So something like
```
  - name: nginx-oci-entrypoint
    description: Entrypoint for using Nginx in OCI containers
    dependencies:
      runtime:
        - bash
    pipeline:
      - runs: |
          mkdir -p ${{targets.subpkgdir}}/var/lib/nginx/initconfig
          cp nginx-entrypoint.sh ${{targets.subpkgdir}}/var/lib/nginx/initconfig/
          chmod +x ${{targets.subpkgdir}}/var/lib/nginx/initconfig/nginx-entrypoint.sh

```

and then add that `nginx-oci-entrypoint` package to the apko yaml in this repo and modify the entry point command
```
entrypoint:
  command: /var/lib/nginx/initconfig/nginx-oci-entrypoint
```

Once [this PR ](https://github.com/chainguard-images/images/pull/227) is merged you should be good to go.  Hopefully that will merge today.
